### ISSUE TITLE
Solve the problem of OOP

### ISSUE THREAD

**Issue by big-vl** [peterhinch/micropython-mqtt#105]
The question is why is everything mixed up in the code? Both WiFi and mqtt client.

**Comment by peterhinch** [comment]
I agree `mqtt_as` should be rewritten. Ideas for this project are offered [here](https://github.com/peterhinch/micropython-mqtt/blob/master/FUTURE_DEVELOPMENT.md), also an explanation of how the module came into being.

Doing it properly is a big job (not least because of the resilience testing), and it's a moot point whether it would still fit on an ESP8266. Feel free to take it on.
