### ISSUE TITLE
[Feature Questions] Unsubscribe, recognize retained messages

### ISSUE THREAD

**Issue by kevinkk525** [peterhinch/micropython-mqtt#6]
Hello Peter,

I implemented the functionality for "unsubscribe" into my fork.
Additionaly I added the possibility to recognize retained publications and pass that information on to the "subs_cb" callback. Because of this, my repository is not a drop-in replacement anymore as it requires the "subs_cb" to accept 3 args (topic,msg,retained). 

I'd be happy if you could take a look at the changes of the [commit](https://github.com/kevinkk525/micropython-mqtt/commit/7120bd0375cab0b886c43647259e21a86b3f117f) adding the functionality. I'm not sure if I missed something but it definitely works as expected.
I'm also writing, because my "experimental" fork is mentioned in your README and with these changes you might be thinking differently about how to mention my fork or if you want to mention it at all, given that the functionality and drop-in ability has changed.

**Comment by peterhinch** [comment]
Hi Kevin, thank you for your contributions. In our previous communications I said I was waiting on a new hardware platform before recommencing work on MQTT. Since then Damien announced it as the Pyboard D series which has onboard WiFi.

My plan (when I get a sample) is as follows:
 * Determine what's involved in porting the library to the new platform.
 * Perform initial resilience testing with it.
 * Review all proposed changes, notably yours. Implement some or all of them.
 * Re-test ESP32 to see if underlying reliability has improved and if the arbitrary delays can be removed.
 * Remove the Sonoff code (I never achieved resilience on the hardware).
 * Repeat reliability and range testing on various platforms.

To avoid repeating work I don't plan to start this until the Pyboard D is in my hands.

**Comment by kevinkk525** [comment]
I completely understand, thanks a lot for your efforts!
Looking forward to the Pyboard D as well :)
